#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidBarBotMaster.Droid.Resource", IsApplication=true)]

namespace DroidBarBotMaster.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070003
			public const int blueL = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int limeB = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int orangeR = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int redO = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int white = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_start = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundlist = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bottleicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonRound = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LogoCocktailGlass = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logoGray = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int myButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int placeholder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int placeholder_white = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002e
			public const int LinearLayout01 = 2131034158;
			
			// aapt resource value: 0x7f050012
			public const int bottletextName1 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int bottletextName2 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int bottletextName3 = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int bottletextName4 = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int bottletextName5 = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int bottletextName6 = 2131034140;
			
			// aapt resource value: 0x7f050026
			public const int btnConnect = 2131034150;
			
			// aapt resource value: 0x7f05002b
			public const int btnDisConnect = 2131034155;
			
			// aapt resource value: 0x7f050002
			public const int btnEdit = 2131034114;
			
			// aapt resource value: 0x7f050029
			public const int btnOrderDrink = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int btnSend = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int btnUpdateBottle = 2131034152;
			
			// aapt resource value: 0x7f050011
			public const int btnedit1 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int btnedit2 = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int btnedit3 = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int btnedit4 = 2131034135;
			
			// aapt resource value: 0x7f050019
			public const int btnedit5 = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int btnedit6 = 2131034139;
			
			// aapt resource value: 0x7f050005
			public const int cocktailListView = 2131034117;
			
			// aapt resource value: 0x7f050023
			public const int drinkImage = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int drinkName = 2131034148;
			
			// aapt resource value: 0x7f05000d
			public const int drinkOrder = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int editPage_title = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int editPage_undetitle = 2131034127;
			
			// aapt resource value: 0x7f050021
			public const int editTextAmount = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int editTextDrinkName = 2131034143;
			
			// aapt resource value: 0x7f050022
			public const int editsave = 2131034146;
			
			// aapt resource value: 0x7f05001d
			public const int imageView = 2131034141;
			
			// aapt resource value: 0x7f05002c
			public const int imageView1 = 2131034156;
			
			// aapt resource value: 0x7f050007
			public const int imageView4 = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050025
			public const int line1 = 2131034149;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout111 = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayoutDrinkOrder = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int scrollView1 = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int scrollViewDrinkOrder = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int searchView1 = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int space1 = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int strDrink = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int strdescription = 2131034124;
			
			// aapt resource value: 0x7f05002d
			public const int tabsHost = 2131034157;
			
			// aapt resource value: 0x7f05002a
			public const int textView1 = 2131034154;
			
			// aapt resource value: 0x7f05001e
			public const int textView2 = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int textView3 = 2131034144;
			
			// aapt resource value: 0x7f05000b
			public const int titledescription = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int view1 = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CocktailListview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DrinkOrder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditPage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listItemDrink = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Start_and_connect = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartBlank = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TabbedPage = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
